export default {
    products: [{
        _id: '1',
        name: 'Silk Saree',
        category: 'saree',
        image: '/images/silk_saree.jpg',
        price: 6000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 5
    },
    {   _id: '2',
        name: 'Kanjeevram Saree',
        category: 'saree',
        image: '/images/kanjeevaram.jpg',
        price: 7000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 5
    },
    {   _id: '3',
        name: 'Bandhani Saree',
        category: 'saree',
        image: '/images/bandhani.jpg',
        price: 10000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 4
    },
    {   _id: '4',
        name: 'Banarasi Saree',
        category: 'saree',
        image: '/images/banarasi.jpg',
        price: 5000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 4
    },
    {   _id: '5',
        name: 'Chanderi Saree',
        category: 'saree',
        image: '/images/chanderi.jpg',
        price: 4000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 4
    },
    {   _id: '6',
        name: 'Kanjeevram Saree',
        category: 'saree',
        image: '/images/kanjeevaram.jpg',
        price: 7000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 5
    },
    {   _id: '7',
        name: 'Bandhani Saree',
        category: 'saree',
        image: '/images/bandhani.jpg',
        price: 10000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 4
    },
    {   _id: '8',
        name: 'Banarasi Saree',
        category: 'saree',
        image: '/images/banarasi.jpg',
        price: 5000,
        brand: 'Manyavar-mohe',
        rating: 4.5,
        numReviews: 10,
        status: 'Available',
        countInStock: 4
    }

]
}